/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ttmt.tuan3.Lab3;

/**
 *
 * @author Lâm Hoàng Minh Tuấn
 */
public class Thietkegamexapsepso extends javax.swing.JFrame {

    /**
     * Creates new form Thietkegamexapsepso
     */
    public Thietkegamexapsepso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPnchinh = new javax.swing.JPanel();
        JPnphu1 = new javax.swing.JPanel();
        chutrochoixepso = new javax.swing.JLabel();
        Jnphu2 = new javax.swing.JPanel();
        batdau = new javax.swing.JButton();
        JPnphu3 = new javax.swing.JPanel();
        so15 = new javax.swing.JButton();
        so14 = new javax.swing.JButton();
        so13 = new javax.swing.JButton();
        so12 = new javax.swing.JButton();
        so11 = new javax.swing.JButton();
        so10 = new javax.swing.JButton();
        so9 = new javax.swing.JButton();
        so8 = new javax.swing.JButton();
        so7 = new javax.swing.JButton();
        so6 = new javax.swing.JButton();
        so5 = new javax.swing.JButton();
        so4 = new javax.swing.JButton();
        so3 = new javax.swing.JButton();
        so2 = new javax.swing.JButton();
        so1 = new javax.swing.JButton();
        otrong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRÒ CHƠI XẾP SỐ");

        JPnchinh.setLayout(new java.awt.BorderLayout());

        chutrochoixepso.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        chutrochoixepso.setText("TRÒ CHƠI XẾP SỐ");
        JPnphu1.add(chutrochoixepso);

        JPnchinh.add(JPnphu1, java.awt.BorderLayout.PAGE_START);

        batdau.setText("Bắt đầu");
        Jnphu2.add(batdau);

        JPnchinh.add(Jnphu2, java.awt.BorderLayout.PAGE_END);

        JPnphu3.setLayout(new java.awt.GridLayout(4, 4));

        so15.setText("15");
        so15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                so15ActionPerformed(evt);
            }
        });
        JPnphu3.add(so15);

        so14.setText("14");
        JPnphu3.add(so14);

        so13.setText("13");
        JPnphu3.add(so13);

        so12.setText("12");
        JPnphu3.add(so12);

        so11.setText("11");
        JPnphu3.add(so11);

        so10.setText("10");
        JPnphu3.add(so10);

        so9.setText("9");
        JPnphu3.add(so9);

        so8.setText("8");
        JPnphu3.add(so8);

        so7.setText("7");
        JPnphu3.add(so7);

        so6.setText("6");
        JPnphu3.add(so6);

        so5.setText("5");
        JPnphu3.add(so5);

        so4.setText("4");
        JPnphu3.add(so4);

        so3.setText("3");
        JPnphu3.add(so3);

        so2.setText("2");
        JPnphu3.add(so2);

        so1.setText("1");
        JPnphu3.add(so1);

        otrong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otrongActionPerformed(evt);
            }
        });
        JPnphu3.add(otrong);

        JPnchinh.add(JPnphu3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPnchinh, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JPnchinh, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void so15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_so15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_so15ActionPerformed

    private void otrongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otrongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otrongActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Thietkegamexapsepso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Thietkegamexapsepso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Thietkegamexapsepso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Thietkegamexapsepso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Thietkegamexapsepso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPnchinh;
    private javax.swing.JPanel JPnphu1;
    private javax.swing.JPanel JPnphu3;
    private javax.swing.JPanel Jnphu2;
    private javax.swing.JButton batdau;
    private javax.swing.JLabel chutrochoixepso;
    private javax.swing.JButton otrong;
    private javax.swing.JButton so1;
    private javax.swing.JButton so10;
    private javax.swing.JButton so11;
    private javax.swing.JButton so12;
    private javax.swing.JButton so13;
    private javax.swing.JButton so14;
    private javax.swing.JButton so15;
    private javax.swing.JButton so2;
    private javax.swing.JButton so3;
    private javax.swing.JButton so4;
    private javax.swing.JButton so5;
    private javax.swing.JButton so6;
    private javax.swing.JButton so7;
    private javax.swing.JButton so8;
    private javax.swing.JButton so9;
    // End of variables declaration//GEN-END:variables
}
